### ISSUE TITLE
Create a Database Schema

### ISSUE THREAD

**Issue by jeramief** [ImanKahlila/ProjectHunt#1]
https://lucid.app/lucidchart/abb93282-2a6a-416a-b3f4-e4df925a4522/edit?viewport_loc=-846%2C-139%2C2163%2C1043%2C4bxQfvkIw3VE&invitationId=inv_b6096bf0-b565-4e82-b2b6-5c6d678c41fe

**Comment by ThomasCarney315** [comment]
For the project table, can you add a field for meeting time(s)

**Comment by Cheesely** [comment]
For users, do you think we should add Class number? It could even be a range. 

- Class 1-20
- Class 21-40
- Class 41-60
- Class 60+



And for projects. I was thinking having a recruiting status could be helpful. That way it's obvious whether a project is:

- actively seeking people
- open to people joining
- not looking for people to join


I know you have tech stack but.. What about the idea of being able to specify what skills would be relevant for the project?

- node.js
- mongoDB
- React
- CSS
- JavaScript
- HTML
- typescript
- postGRE
- otherss...

**Comment by andrewquach-dev** [comment]
> * actively seeking people
> * open to people joining
> * not looking for people to join

Good point! Timezone is a bit broad but having a meeting time(s) column can narrow it down.

**Comment by andrewquach-dev** [comment]
> For users, do you think we should add Class number? It could even be a range.
> 
> * Class 1-20
> * Class 21-40
> * Class 41-60
> * Class 60+
> 
> And for projects. I was thinking having a recruiting status could be helpful. That way it's obvious whether a project is:
> 
> * actively seeking people
> * open to people joining
> * not looking for people to join
> 
> I know you have tech stack but.. What about the idea of being able to specify what skills would be relevant for the project?
> 
> * node.js
> * mongoDB
> * React
> * CSS
> * JavaScript
> * HTML
> * typescript
> * postGRE
> * otherss...

Great suggestions! Regarding your first point, a class number schema might not apply to other organizations like freecodecamp or theodinproject so I was thinking of switching it to skill level or proficiency level. Also, I had the same idea for recruiting status and added status to the schema already. We can use those status states you mentioned. Lastly, I was hoping to use tech stack to describe the set of technologies that will be used in a project but skills might be more fitting because it encompasses a wider range of focuses.

**Comment by Cheesely** [comment]
That's a good point Andrew. But once we add other code camps, we can customize that field. So for Learn with Leon the field would look one way and for other code camps the field would look another way. I think it's called an isomorphic relationship..

**Comment by Cheesely** [comment]
Also I'm not sure how Mongo handles relationships. Should there be a relationship between user and group? Do that a user can join a group?

**Comment by andrewquach-dev** [comment]
I did some research on if it's possible to have a conditional column on a model schema so that if the organization was Learn with Leon then class number would be an option but I've never done anything like that before so we can definitely try to figure something out. 

For skill, I also had those options in mind. Something like: Beginner, Intermediate, Advanced, Expert

After taking another look at the DB schema, I realized there isn't a relationship other than the creator user and the project. We might have to create a Group schema to store information about the association between users and projects.
